name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python Windows
        if: matrix.os == 'windows-latest'
        uses: actions/setup-python@v4
        with:
          python-version: 3.7.7

      - name: Set up Python Mac
        if: matrix.os == 'macos-latest'
        uses: actions/setup-python@v4
        with:
          python-version: 3.7.7

      - name: Set up Python ubuntu
        if: matrix.os == 'ubuntu-latest'
        uses: actions/setup-python@v4
        with:
          python-version: 3.7.15

      - name: Installer Create DMG
        if: matrix.os == 'macos-latest'
        run: brew install create-dmg

      - name: Install Requirement
        run: pip install -r requirements.txt

      - name: Run Pyinstaller
        run: python pkg.py

      - name: NSIS (windows)
        if: matrix.os == 'windows-latest'
        uses: joncloud/makensis-action@v4

      - name: Create Dmg (Mac)
        if: matrix.os == 'macos-latest'
        run: create-dmg --volname "WeDuck" --window-pos 200 220 --window-size 500 300 --icon-size 100 --icon "WeDuck.app" 100 100 --hide-extension "WeDuck.app" --app-drop-link 300 100 "WeDuckInstaller.dmg" "dist/WeDuck.app"

      - name: Upload Exe (windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          path: WeDuckInstall.exe

      - name: Upload Dmg (Mac)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          path: rw.WeDuckInstaller.dmg