name: Build

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions: write-all

    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pip'
          
      - name: Upgrade "pip"
        run: python -m pip install --upgrade pip

      - name: Installer Create DMG
        if: matrix.os == 'macos-latest'
        run: brew install create-dmg

      - name: Install Requirement
        run: pip install -r requirements.txt

      - name: Run Pyinstaller
        run: python pkg.py

      - name: NSIS (windows)
        if: matrix.os == 'windows-latest'
        uses: joncloud/makensis-action@v4

      - name: Create Dmg (Mac)
        if: matrix.os == 'macos-latest'
        run: create-dmg --volname "WeDuck" --window-pos 200 220 --window-size 500 300 --icon-size 100 --icon "WeDuck.app" 100 100 --hide-extension "WeDuck.app" --app-drop-link 300 100 "WeDuckInstall.dmg" "dist/WeDuck.app"

      - name: Upload dmg
        if: matrix.os == 'macos-latest'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          prerelease: false
          files: WeDuckInstall.dmg

      - name: Upload exe
        if: matrix.os == 'windows-latest'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          prerelease: false
          files: WeDuckInstall.exe
